name: ocsmesh
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - gdal
  - geos
  - proj
  - netcdf4
  - udunits2
  - pyproj
  - shapely
  - rasterio
  - fiona
  - geopandas
  - utm
  - scipy
  - numba
  - numpy>=1.21 # numpy.typing
  - matplotlib
  - mpi4py
  - pyarrow
  - pytz
  - colored-traceback
  - typing-extensions
