name: ocsmesh-env
channels:
  - conda-forge
dependencies:
  - python
  - gdal
  - geos
  - proj
  - netcdf4
  - udunits2
  - pyproj
  - shapely<1.8
  - rasterio
  - fiona
  - pygeos
  - geopandas
  - utm
  - scipy<1.8
  - numpy>=1.21
  - matplotlib
  - requests
  - tqdm
  - mpi4py
  - pyarrow
  - pytz
  - geoalchemy2
  - colored-traceback
  - typing-extensions
